// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    /// Get coordinates
    ///
    /// Direct geocoding allows to get geographical coordinates (lat, lon) by using name of the location (city name or area name).
    static public func directGeocode(q: String) -> Request<[OpenWeatherAPI.LocationData]> {
        Request(path: "/geo/1.0/direct", method: "GET", query: [("q", q)], id: "directGeocode")
    }
}
