// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    /// Get name of the location
    ///
    /// Reverse geocoding allows to get name of the location (city name or area name) by using geografical coordinates (lat, lon).
    static public func reverseGeocode(lat: String, lon: String) -> Request<[OpenWeatherAPI.LocationData]> {
        Request(path: "/geo/1.0/reverse", method: "GET", query: [("lat", lat), ("lon", lon)], id: "reverseGeocode")
    }
}
