// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ForecastData: Codable, Hashable {
    /// Time of data calculation, unix, UTC
    public var dt: Int32
    /// Temperature. Units - default: Kelvin, metric: Celsius, imperial: Fahrenheit.
    public var temp: Double
    /// Humidity, %
    public var humidity: Int32
    /// Wind speed. Units - default: meter/sec, metric: meter/sec, imperial: miles/hour.
    public var windSpeed: Double
    /// Wind direction, degrees (meteorological)
    public var windDeg: Int32
    /// (more info Weather condition codes)
    public var weather: [Weather]

    public init(dt: Int32, temp: Double, humidity: Int32, windSpeed: Double, windDeg: Int32, weather: [Weather]) {
        self.dt = dt
        self.temp = temp
        self.humidity = humidity
        self.windSpeed = windSpeed
        self.windDeg = windDeg
        self.weather = weather
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.dt = try values.decode(Int32.self, forKey: "dt")
        self.temp = try values.decode(Double.self, forKey: "temp")
        self.humidity = try values.decode(Int32.self, forKey: "humidity")
        self.windSpeed = try values.decode(Double.self, forKey: "wind_speed")
        self.windDeg = try values.decode(Int32.self, forKey: "wind_deg")
        self.weather = try values.decode([Weather].self, forKey: "weather")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(dt, forKey: "dt")
        try values.encode(temp, forKey: "temp")
        try values.encode(humidity, forKey: "humidity")
        try values.encode(windSpeed, forKey: "wind_speed")
        try values.encode(windDeg, forKey: "wind_deg")
        try values.encode(weather, forKey: "weather")
    }
}
