// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct LocationForecast: Codable, Hashable {
    /// City geo location, longitude
    public var lon: Double
    /// City geo location, latitude
    public var lat: Double
    public var current: ForecastData
    /// Hourly forecast weather data
    public var hourly: [ForecastData]
    /// Daily forecast weather data
    public var daily: [DailyForecastData]

    public init(lon: Double, lat: Double, current: ForecastData, hourly: [ForecastData], daily: [DailyForecastData]) {
        self.lon = lon
        self.lat = lat
        self.current = current
        self.hourly = hourly
        self.daily = daily
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.lon = try values.decode(Double.self, forKey: "lon")
        self.lat = try values.decode(Double.self, forKey: "lat")
        self.current = try values.decode(ForecastData.self, forKey: "current")
        self.hourly = try values.decode([ForecastData].self, forKey: "hourly")
        self.daily = try values.decode([DailyForecastData].self, forKey: "daily")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(lon, forKey: "lon")
        try values.encode(lat, forKey: "lat")
        try values.encode(current, forKey: "current")
        try values.encode(hourly, forKey: "hourly")
        try values.encode(daily, forKey: "daily")
    }
}
