// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct LocationData: Codable {
    /// Name of the found location
    public var name: String?
    public var localNames: [String: String]?
    /// Geographical coordinates of the found location (longitude)
    public var lat: Double?
    /// Geographical coordinates of the found location (latitude)
    public var lon: Double?
    /// Country of the found location
    public var country: String?

    public init(name: String? = nil, localNames: [String: String]? = nil, lat: Double? = nil, lon: Double? = nil, country: String? = nil) {
        self.name = name
        self.localNames = localNames
        self.lat = lat
        self.lon = lon
        self.country = country
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decodeIfPresent(String.self, forKey: "name")
        self.localNames = try values.decodeIfPresent([String: String].self, forKey: "local_names")
        self.lat = try values.decodeIfPresent(Double.self, forKey: "lat")
        self.lon = try values.decodeIfPresent(Double.self, forKey: "lon")
        self.country = try values.decodeIfPresent(String.self, forKey: "country")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(localNames, forKey: "local_names")
        try values.encodeIfPresent(lat, forKey: "lat")
        try values.encodeIfPresent(lon, forKey: "lon")
        try values.encodeIfPresent(country, forKey: "country")
    }
}
