// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct OnecallResponse: Codable {
    /// City geo location, longitude
    public var lon: Double?
    /// City geo location, latitude
    public var lat: Double?
    public var current: ForecastData?
    /// Hourly forecast weather data
    public var hourly: [ForecastData]?
    /// Daily forecast weather data
    public var daily: [ForecastData]?

    public init(lon: Double? = nil, lat: Double? = nil, current: ForecastData? = nil, hourly: [ForecastData]? = nil, daily: [ForecastData]? = nil) {
        self.lon = lon
        self.lat = lat
        self.current = current
        self.hourly = hourly
        self.daily = daily
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.lon = try values.decodeIfPresent(Double.self, forKey: "lon")
        self.lat = try values.decodeIfPresent(Double.self, forKey: "lat")
        self.current = try values.decodeIfPresent(ForecastData.self, forKey: "current")
        self.hourly = try values.decodeIfPresent([ForecastData].self, forKey: "hourly")
        self.daily = try values.decodeIfPresent([ForecastData].self, forKey: "daily")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(lon, forKey: "lon")
        try values.encodeIfPresent(lat, forKey: "lat")
        try values.encodeIfPresent(current, forKey: "current")
        try values.encodeIfPresent(hourly, forKey: "hourly")
        try values.encodeIfPresent(daily, forKey: "daily")
    }
}
