// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Weather: Codable {
    /// Weather condition id
    public var id: Int32?
    /// Group of weather parameters (Rain, Snow, Extreme etc.)
    ///
    /// Example: "Clouds"
    public var main: String?
    /// Weather condition within the group
    public var description: String?
    /// Weather icon id
    public var icon: String?

    public init(id: Int32? = nil, main: String? = nil, description: String? = nil, icon: String? = nil) {
        self.id = id
        self.main = main
        self.description = description
        self.icon = icon
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int32.self, forKey: "id")
        self.main = try values.decodeIfPresent(String.self, forKey: "main")
        self.description = try values.decodeIfPresent(String.self, forKey: "description")
        self.icon = try values.decodeIfPresent(String.self, forKey: "icon")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(main, forKey: "main")
        try values.encodeIfPresent(description, forKey: "description")
        try values.encodeIfPresent(icon, forKey: "icon")
    }
}
